# Generated by Django 6.0.5 on 2026-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
