# Generated by Django 6.0.5 on 2026-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=7),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, help_text='Days until access expires'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
