# Generated by Django 6.0.5 on 2026-06-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Direct Cloudinary URL', max_length=800, null=True),
        ),
    ]
